# Generated by Django 5.2.12 on 2026-03-24 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên truyện')),
                ('author', models.CharField(max_length=100, verbose_name='Tác giả')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Ảnh bìa')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mật khẩu (để trống nếu mở)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Truyện',
                'verbose_name_plural': 'Truyện',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(verbose_name='Số chương')),
                ('title', models.CharField(max_length=200, verbose_name='Tên chương')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='stories.story', verbose_name='Truyện')),
            ],
            options={
                'verbose_name': 'Chương',
                'verbose_name_plural': 'Chương',
                'ordering': ['chapter_number'],
                'unique_together': {('story', 'chapter_number')},
            },
        ),
    ]
